[package]
name = "tetris_core"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-iterator = "1.4.1"
enum-map = "2.5.0"
itertools = { version = "0.10.5", default-features = false } 
rand = { version = "0.5.0", default-features = false, features = ["alloc"] }
rand_derive = "0.5.0"
