[package]
name = "gb_int"
version = "0.1.0"
authors = ["Blake Loring <blake@parsed.uk>"]
edition = "2021"

[profile.dev]
overflow-checks = false

[dependencies]
log = "0.4.17"
serde = { version = "1.0.159", default-features = false, features = ["derive", "alloc"] }
